In [27]:
import tensorflow as tf
# 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant()
vector = tf.constant([1, 2])
scalar = tf.constant(3)
matrix = tf.constant([[4, 5],
                      [6, 7]])
unchangeable_tensor = tf.constant([8, 9])

# 2. Find the shape, rank and size of the tensors you created in 1.
print("Форма вектора:", vector.shape)
print("Форма скаляра:", scalar.shape)
print("Форма матрицы:", matrix.shape)
print("Форма неизменяемого тензора:", unchangeable_tensor.shape)

print("Ранг вектора:", tf.rank(vector).numpy())
print("Ранг скаляра:", tf.rank(scalar).numpy())
print("Ранг матрицы:", tf.rank(matrix).numpy())
print("Ранг неизменяемого тензора:", tf.rank(unchangeable_tensor).numpy())

print("Размер вектора:", tf.size(vector).numpy())
print("Размер скаляра:", tf.size(scalar).numpy())
print("Размер матрицы:", tf.size(matrix).numpy())
print("Размер неизменяемого тензора:", tf.size(unchangeable_tensor).numpy())

# 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].
tensor1 = tf.random.uniform(shape=[5, 300])
tensor2 = tf.random.uniform(shape=[5, 300])
print("Тензор 1:\n", tensor1.numpy())
print("Тензор 2:\n", tensor2.numpy())

# 4. Multiply the two tensors you created in 3 using matrix multiplication.
matmul_tensors = tf.matmul(tensor1, tf.transpose(tensor2))
print("Матричное умножение тензоров:\n", matmul_tensors.numpy())

# 5. Multiply the two tensors you created in 3 using dot product.
dot_product = tf.tensordot(tf.transpose(tensor1), tensor2, axes=1)
print("Cкалярное произведение тензоров:", dot_product.numpy())

# 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
tensor3 = tf.random.uniform(shape=[224, 224, 3])
print("Тензор с формой [224, 224, 3]:\n", tensor3.numpy())

# 7. Find the min and max values of the tensor you created in 6.
min_value = tf.reduce_min(tensor3)
max_value = tf.reduce_max(tensor3)
print("Минимальное значение:", min_value.numpy())
print("Максимальное значение:", max_value.numpy())

# 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
tensor4 = tf.random.uniform(shape=[1, 224, 224, 3])
squeezed_tensor = tf.squeeze(tensor4)
print("Форма исходного тензора:", tensor4.shape)
print("Форма измененного тензора:", squeezed_tensor.shape)

# 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
tensor5 = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
index_max_value = tf.argmax(tensor5)
print("Тензор 5:", tensor5.numpy())
print("Индекс максимального значения тензора 5:", index_max_value.numpy())

# 10. One-hot encode the tensor you created in 9.
one_hot_tensor = tf.one_hot(tensor5, depth=11)
print("One-hot encoded тензор 5:\n", one_hot_tensor.numpy())

Форма вектора: (2,)
Форма скаляра: ()
Форма матрицы: (2, 2)
Форма неизменяемого тензора: (2,)
Ранг вектора: 1
Ранг скаляра: 0
Ранг матрицы: 2
Ранг неизменяемого тензора: 1
Размер вектора: 2
Размер скаляра: 1
Размер матрицы: 4
Размер неизменяемого тензора: 2
Тензор 1:
 [[0.06930363 0.00647724 0.45361876 ... 0.11889899 0.23582637 0.3410946 ]
 [0.69550085 0.6878164  0.92815053 ... 0.21922624 0.32011116 0.4872712 ]
 [0.91262484 0.6075709  0.49489915 ... 0.7054837  0.75968134 0.8712921 ]
 [0.10798347 0.3523872  0.44283557 ... 0.8530903  0.64379466 0.29960668]
 [0.5149447  0.51916444 0.22940695 ... 0.7978927  0.54659235 0.85837376]]
Тензор 2:
 [[0.5128466  0.11683285 0.5091957  ... 0.42630124 0.20633852 0.3609774 ]
 [0.03860462 0.9242587  0.89455605 ... 0.9532074  0.16570187 0.93937063]
 [0.07723761 0.45757246 0.05788755 ... 0.10116351 0.24761868 0.31247222]
 [0.31394303 0.09108567 0.52968395 ... 0.30791914 0.77485573 0.6731374 ]
 [0.36456144 0.28706396 0.78318536 ... 0.56418574 0.6303687  0